/**
 * Google Workspace Personal Work OS v2 - pre-pilot remediation configuration.
 *
 * This file is intentionally free of Spreadsheet writes and external service calls.
 */
var WorkOsConfig = Object.freeze({
  SYSTEM_NAME: 'Google Workspace Personal Work OS v2',
  CODE_VERSION: '2.8.1-prepilot',
  SCHEMA_VERSION: '2.2',
  AI_SCHEMA_VERSION: '2.0',
  MIGRATION_VERSION: '0',
  TIMEZONE: 'Asia/Tokyo',
  HEADER_ID_ROW: 1,
  HEADER_LABEL_ROW: 2,
  DATA_START_ROW: 3,
  TASK_INITIAL_ROWS: 100,
  SETTINGS_INITIAL_ROWS: 50,
  DEFAULT_INITIAL_ROWS: 100,
  ROW_EXPANSION_UNIT: 100,
  SETUP_SOFT_LIMIT_MS: 120000,
  SETUP_RESERVE_MS: 5000,
  QUICK_DIAGNOSTIC_TARGET_MS: 60000,
  QUICK_DIAGNOSTIC_RESERVE_MS: 5000,
  QUICK_DIAGNOSTIC_CHUNK_ROWS: 250,
  DASHBOARD_SOFT_LIMIT_MS: 60000,
  DASHBOARD_RESERVE_MS: 5000,
  LOCK_WAIT_MS: 5000,
  MANUAL_WORKER_SOFT_LIMIT_MS: 120000,
  MANUAL_WORKER_RESERVE_MS: 5000,
  MANUAL_GMAIL_QUERY: 'label:謇句虚/蜿冶ｾｼ -label:謇句虚/髯､螟・,
  MANUAL_MAX_THREADS: 10,
  MANUAL_MAX_MESSAGES: 1,
  MANUAL_GMAIL_API_CALL_LIMIT: 20,
  CALENDAR_MAX_JOBS_PER_RUN: 1,
  CALENDAR_SEARCH_WINDOW_DAYS: 7,
  CALENDAR_LIST_PAGE_SIZE: 250,
  CALENDAR_LIST_MAX_PAGES: 10,
  MESSAGE_STALE_CLAIM_MS: 30 * 60 * 1000,
  EMAIL_BODY_MAX_CHARS: 20000,
  EMAIL_CONTEXT_MAX_MESSAGES: 2,
  EMAIL_CONTEXT_MAX_CHARS: 2000,
  MAX_AI_ACTIONS: 10,
  MAX_AI_WARNINGS: 10,
  AI_REQUEST_TIMEOUT_MS: 60000,
  AI_RESPONSE_MAX_CHARS: 100000,
  V2_EXTENSION_CHUNK_ROWS: 500,
  V2_EXTENSION_MAX_ROWS: 10000,
  V2_EXTENSION_BUDGET_RESERVE_MS: 5000,
  MOCK_AI_MODEL: 'work-os-deterministic-mock-v2',
  MOCK_PROMPT_VERSION: 'phase3-mock-v1',
  AI_PROVIDER: 'MOCK',
  EXTERNAL_AI_ENABLED: false,
  EXTERNAL_AI_PROVIDER: '',
  EXTERNAL_AI_MODEL: '',
  EXTERNAL_AI_PROMPT_VERSION: '',
  EXTERNAL_AI_CREDENTIAL_REFERENCE: '',
  EXTERNAL_AI_COMPANY_APPROVED: false,
  EXTERNAL_AI_DATA_POLICY_APPROVED: false,
  EXTERNAL_AI_CREDENTIAL_STORAGE_APPROVED: false,
  EXTERNAL_AI_AUTH_CONFIGURED: false,
  AUTOMATION_ENABLED: false,
  AUTOMATION_INTERVAL_MINUTES: 5,
  AUTOMATION_OVERLAP_MS: 24 * 60 * 60 * 1000,
  AUTOMATION_MAX_MESSAGES_PER_RUN: 10,
  AUTOMATION_MAX_SEARCH_THREADS: 100,
  AUTOMATION_SEARCH_PAGE_SIZE: 25,
  AUTOMATION_GMAIL_API_CALL_LIMIT: 160,
  AUTOMATION_WORKER_SOFT_LIMIT_MS: 210000,
  AUTOMATION_WORKER_RESERVE_MS: 5000,
  AUTOMATION_HANDLER_FUNCTION: 'runScheduledWorker',
  EDIT_HANDLER_FUNCTION: 'handleTaskEdit',
  AUTOMATION_NEWSLETTER_FILTER_APPROVED: false,
  AUTOMATION_CALENDAR_NOTIFICATION_FILTER_APPROVED: false,
  AUTOMATION_GMAIL_QUERY:
    'in:inbox -in:spam -in:trash -label:謇句虚/髯､螟・,
  RETRY_DELAYS_MINUTES: Object.freeze([5, 15, 60]),
  RETRY_MAX_ATTEMPTS: 4,
  RETRY_MAX_ITEMS_PER_RUN: 10,
  MANUAL_RETRY_MAX_SELECTED: 5,
  PROVIDER_FAILURE_SUPPRESSION_MS: 5 * 60 * 1000,
  DEEP_DIAGNOSTIC_SOFT_LIMIT_MS: 180000,
  DEEP_DIAGNOSTIC_SAMPLE_ROWS: 50,
  DEADLINE_CALENDAR_NAME: '閾ｪ蜍墓悄譌･邂｡逅・,
  GMAIL_LABELS: Object.freeze([
    'AI/隕∝ｯｾ蠢・,
    'AI/譛滄剞',
    'AI/霑比ｿ｡蠕・,
    'AI/隕∫｢ｺ隱・,
    '謇句虚/蜿冶ｾｼ',
    '謇句虚/髯､螟・,
    'SYS/螟ｱ謨・
  ]),
  SHEETS: Object.freeze({
    DASHBOARD: '繝繝・す繝･繝懊・繝・,
    TASKS: '繧ｿ繧ｹ繧ｯ荳隕ｧ',
    SETTINGS: '險ｭ螳・,
    RUN_HISTORY: '蜃ｦ逅・ｱ･豁ｴ',
    ERRORS: '繧ｨ繝ｩ繝ｼ繝ｻ蜀榊ｮ溯｡・,
    GUIDE: '菴ｿ縺・婿',
    MESSAGE_STATE: '繝｡繝ｼ繝ｫ迥ｶ諷・,
    SYSTEM_CONFIG: '繧ｷ繧ｹ繝・Β險ｭ螳・,
    PROMPT_VERSIONS: '繝励Ο繝ｳ繝励ヨ迚育ｮ｡逅・,
    SYNC_STATE: '蜷梧悄迥ｶ諷・
  }),
  V1_SHEET_NAMES: Object.freeze([
    '隕∫｢ｺ隱・,
    'Review Queue',
    'review_queue',
    'system_config',
    'history',
    'task_master',
    '繝｡繝ｼ繝ｫ荳隕ｧ'
  ]),
  PROPERTIES: Object.freeze({
    INSTANCE_ID: 'WORK_OS_V2_INSTANCE_ID',
    CODE_VERSION: 'WORK_OS_V2_CODE_VERSION',
    SCHEMA_VERSION: 'WORK_OS_V2_SCHEMA_VERSION',
    MIGRATION_VERSION: 'WORK_OS_V2_MIGRATION_VERSION',
    SETUP_COMPLETED_STAGES: 'WORK_OS_V2_SETUP_COMPLETED_STAGES',
    SETUP_LAST_RESULT: 'WORK_OS_V2_SETUP_LAST_RESULT',
    MANAGEMENT_EDIT_WARNING: 'WORK_OS_V2_MANAGEMENT_EDIT_WARNING',
    DEADLINE_CALENDAR_ID: 'WORK_OS_V2_DEADLINE_CALENDAR_ID',
    AUTOMATION_ENABLED: 'WORK_OS_V2_AUTOMATION_ENABLED',
    AUTOMATION_DESIRED_STATE: 'WORK_OS_V2_AUTOMATION_DESIRED_STATE',
    AUTOMATION_TRIGGER_ID: 'WORK_OS_V2_AUTOMATION_TRIGGER_ID',
    EDIT_TRIGGER_ID: 'WORK_OS_V2_EDIT_TRIGGER_ID',
    AUTOMATION_WATERMARK_AT: 'WORK_OS_V2_AUTOMATION_WATERMARK_AT',
    AUTOMATION_LAST_RUN_AT: 'WORK_OS_V2_AUTOMATION_LAST_RUN_AT',
    AUTOMATION_SCAN_UPPER_AT: 'WORK_OS_V2_AUTOMATION_SCAN_UPPER_AT',
    AUTOMATION_SCAN_PAGE_TOKEN:
      'WORK_OS_V2_AUTOMATION_SCAN_PAGE_TOKEN',
    AI_PROVIDER_SUPPRESS_UNTIL:
      'WORK_OS_V2_AI_PROVIDER_SUPPRESS_UNTIL'
  }),
  SETUP_STAGES: Object.freeze([
    'S00_VALIDATE_ENV',
    'S10_CREATE_SHEETS',
    'S20_CREATE_SCHEMAS',
    'S30_APPLY_SMALL_VALIDATIONS',
    'S40_SEED_SAFE_SETTINGS',
    'S50_CREATE_GMAIL_LABELS',
    'S60_CREATE_DEADLINE_CALENDAR',
    'S70_STORE_PROPERTIES',
    'S80_CREATE_EDIT_TRIGGER',
    'S90_QUICK_DIAGNOSTIC',
    'S99_COMPLETE'
  ]),
  IMPLEMENTED_SETUP_STAGES: Object.freeze([
    'S00_VALIDATE_ENV',
    'S10_CREATE_SHEETS',
    'S20_CREATE_SCHEMAS',
    'S30_APPLY_SMALL_VALIDATIONS',
    'S40_SEED_SAFE_SETTINGS',
    'S50_CREATE_GMAIL_LABELS',
    'S60_CREATE_DEADLINE_CALENDAR',
    'S70_STORE_PROPERTIES',
    'S80_CREATE_EDIT_TRIGGER',
    'S90_QUICK_DIAGNOSTIC',
    'S99_COMPLETE'
  ]),
  DATE_FORMAT: 'yyyy/mm/dd',
  DATETIME_FORMAT: 'yyyy/mm/dd hh:mm:ss',
  TEST_MODE: true
});

var WorkOsEnums = Object.freeze({
  TaskStatus: Object.freeze({
    REVIEW: '隕∫｢ｺ隱・,
    OPEN: '譛ｪ蟇ｾ蠢・,
    IN_PROGRESS: '蟇ｾ蠢應ｸｭ',
    WAITING: '霑比ｿ｡蠕・■',
    DONE: '螳御ｺ・,
    EXCLUDED: '蟇ｾ雎｡螟・,
    CANCELLED: '蜿匁ｶ・
  }),
  Decision: Object.freeze({
    NONE: '譛ｪ驕ｸ謚・,
    ACCEPT: '蜿怜・',
    REJECT: '蜊ｴ荳・
  }),
  Priority: Object.freeze({
    HIGH: '鬮・,
    MEDIUM: '荳ｭ',
    LOW: '菴・
  }),
  DeadlineBasis: Object.freeze({
    EXPLICIT: '譏守､ｺ',
    RELATIVE: '逶ｸ蟇ｾ',
    INFERRED: '謗ｨ貂ｬ',
    AMBIGUOUS: '譖匁乂',
    NONE: '縺ｪ縺・
  }),
  CalendarSyncMode: Object.freeze({
    AUTO: '閾ｪ蜍・,
    FORCE: '逋ｻ骭ｲ',
    NONE: '蟇ｾ雎｡螟・
  }),
  ReviewState: Object.freeze({
    NONE: '縺ｪ縺・,
    OPEN: '譛ｪ遒ｺ隱・,
    APPLIED: '驕ｩ逕ｨ貂・,
    REJECTED: '蜊ｴ荳区ｸ・
  }),
  CalendarImportance: Object.freeze({
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH'
  }),
  CalendarSyncStatus: Object.freeze({
    NOT_REQUIRED: 'NOT_REQUIRED',
    PENDING: 'PENDING',
    SYNCED: 'SYNCED',
    DELETE_PENDING: 'DELETE_PENDING',
    ERROR: 'ERROR'
  }),
  ScheduleState: Object.freeze({
    NONE: 'NONE',
    FUTURE: 'FUTURE',
    UPCOMING: 'UPCOMING',
    TODAY: 'TODAY',
    OVERDUE: 'OVERDUE'
  })
});

var WorkOsSheetOrder = Object.freeze([
  WorkOsConfig.SHEETS.DASHBOARD,
  WorkOsConfig.SHEETS.TASKS,
  WorkOsConfig.SHEETS.SETTINGS,
  WorkOsConfig.SHEETS.RUN_HISTORY,
  WorkOsConfig.SHEETS.ERRORS,
  WorkOsConfig.SHEETS.GUIDE,
  WorkOsConfig.SHEETS.MESSAGE_STATE,
  WorkOsConfig.SHEETS.SYSTEM_CONFIG,
  WorkOsConfig.SHEETS.PROMPT_VERSIONS,
  WorkOsConfig.SHEETS.SYNC_STATE
]);

var WorkOsHiddenSheets = Object.freeze([
  WorkOsConfig.SHEETS.MESSAGE_STATE,
  WorkOsConfig.SHEETS.SYSTEM_CONFIG,
  WorkOsConfig.SHEETS.PROMPT_VERSIONS,
  WorkOsConfig.SHEETS.SYNC_STATE
]);

